services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: diskentulho_api
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DiskEntulhoDB;User Id=sa;Password=DiskEntulho@123;TrustServerCertificate=True;
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diskentulho_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: diskentulho_db
    environment:
      SA_PASSWORD: "DiskEntulho@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "DiskEntulho@123", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
